import { config, library, dom } from '@fortawesome/fontawesome-svg-core'

config.mutateApproach = 'sync'

import {
  faAddressCard,
  faBarcode,
  faBriefcase,
  faCalendar,
  faCalendarCheck,
  faCalendarXmark,
  faCheck,
  faCheckDouble,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faCircleXmark,
  faChevronLeft,
  faFileLines,
  faFlag,
  faFolderPlus,
  faGlobe,
  faGraduationCap,
  faLink,
  faList,
  faMaximize,
  faPaperclip,
  faPenToSquare,
  faPlay,
  faRightFromBracket,
  faRightToBracket,
  faSearch,
  faTrash,
  faUser
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faAddressCard,
  faBarcode,
  faBriefcase,
  faCalendar,
  faCalendarCheck,
  faCalendarXmark,
  faCheck,
  faCheckDouble,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faCircleXmark,
  faChevronLeft,
  faFileLines,
  faFlag,
  faFolderPlus,
  faGlobe,
  faGraduationCap,
  faLink,
  faList,
  faMaximize,
  faPaperclip,
  faPenToSquare,
  faPlay,
  faRightFromBracket,
  faRightToBracket,
  faSearch,
  faTrash,
  faUser
)

dom.watch()
